{{/*
=============================================================================
FastAPI Secret Template
Author: bekiryagan
=============================================================================
*/}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi.fullname" . }}-secrets
  labels:
    {{- include "fastapi.labels" . | nindent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
