# =============================================================================
# Redis High Availability Cluster
# Author: Bekir Yagan
# =============================================================================
# Redis with Sentinel for automatic failover:
# - 1 Master + 2 Replicas
# - Sentinel for monitoring and failover
# - Persistent storage
# - Memory and connection limits
# =============================================================================

---
# Redis Master StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-master
  namespace: database
  labels:
    app: redis
    role: master
spec:
  serviceName: redis-master
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9121"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      
      containers:
        - name: redis
          image: redis:7.2-alpine
          command:
            - redis-server
            - /etc/redis/redis.conf
          
          ports:
            - name: redis
              containerPort: 6379
          
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
            - name: tmp
              mountPath: /tmp
          
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
          
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
        
        # Redis Exporter
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.55.0
          ports:
            - name: metrics
              containerPort: 9121
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: password
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
      
      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: tmp
          emptyDir: {}
  
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 10Gi
---
# Redis Replica StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-replica
  namespace: database
  labels:
    app: redis
    role: replica
spec:
  serviceName: redis-replica
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: replica
  template:
    metadata:
      labels:
        app: redis
        role: replica
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      
      containers:
        - name: redis
          image: redis:7.2-alpine
          command:
            - redis-server
            - /etc/redis/redis-replica.conf
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/redis
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 3
      
      volumes:
        - name: config
          configMap:
            name: redis-config
        - name: tmp
          emptyDir: {}
  
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: fast-ssd
        resources:
          requests:
            storage: 10Gi
---
# Redis Sentinel Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-sentinel
  namespace: database
  labels:
    app: redis-sentinel
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis-sentinel
  template:
    metadata:
      labels:
        app: redis-sentinel
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      
      containers:
        - name: sentinel
          image: redis:7.2-alpine
          command:
            - redis-sentinel
            - /etc/redis/sentinel.conf
          ports:
            - name: sentinel
              containerPort: 26379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: config
              mountPath: /etc/redis
            - name: data
              mountPath: /data
      
      volumes:
        - name: config
          configMap:
            name: redis-sentinel-config
        - name: data
          emptyDir: {}
---
# Redis Services
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: database
  labels:
    app: redis
    role: master
spec:
  type: ClusterIP
  selector:
    app: redis
    role: master
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-replica
  namespace: database
  labels:
    app: redis
    role: replica
spec:
  type: ClusterIP
  selector:
    app: redis
    role: replica
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-sentinel
  namespace: database
spec:
  type: ClusterIP
  selector:
    app: redis-sentinel
  ports:
    - name: sentinel
      port: 26379
      targetPort: 26379
---
# Redis ConfigMaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: database
data:
  redis.conf: |
    # Master configuration
    bind 0.0.0.0
    port 6379
    protected-mode yes
    requirepass REDIS_PASSWORD_PLACEHOLDER
    
    # Persistence
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    
    # Memory management
    maxmemory 1500mb
    maxmemory-policy allkeys-lru
    
    # Performance
    tcp-keepalive 300
    timeout 0
    tcp-backlog 511
    
    # Logging
    loglevel notice
    logfile ""
    
    # Security
    rename-command FLUSHALL ""
    rename-command FLUSHDB ""
    rename-command DEBUG ""
  
  redis-replica.conf: |
    bind 0.0.0.0
    port 6379
    protected-mode yes
    requirepass REDIS_PASSWORD_PLACEHOLDER
    masterauth REDIS_PASSWORD_PLACEHOLDER
    
    # Replication
    replicaof redis-master.database.svc.cluster.local 6379
    replica-read-only yes
    
    # Persistence
    appendonly yes
    appendfsync everysec
    
    # Memory
    maxmemory 1500mb
    maxmemory-policy allkeys-lru
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-sentinel-config
  namespace: database
data:
  sentinel.conf: |
    port 26379
    sentinel monitor mymaster redis-master.database.svc.cluster.local 6379 2
    sentinel auth-pass mymaster REDIS_PASSWORD_PLACEHOLDER
    sentinel down-after-milliseconds mymaster 5000
    sentinel failover-timeout mymaster 60000
    sentinel parallel-syncs mymaster 1
---
# Redis Secrets
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: database
type: Opaque
stringData:
  password: "REPLACE_IN_PRODUCTION"
